# Generated by Django 5.2.3 on 2025-06-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tbAssociados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_responsavel", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=14)),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("aluno", models.CharField(max_length=255)),
                ("nome_de_guerra", models.CharField(max_length=255)),
                ("codigo_associado", models.CharField(max_length=50)),
            ],
        ),
    ]
