# Generated by Django 5.2.1 on 2025-06-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Usuarios",
            new_name="Usuario",
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "ordering": ["nome"],
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
    ]
