# Generated by Django 5.2.1 on 2025-06-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0002_rename_usuarios_usuario_alter_usuario_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "ordering": ["nome"],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.AlterField(
            model_name="usuario",
            name="idade",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.TextField(max_length=100),
        ),
    ]
